In [8]:
% load_ext autoreload
% autoreload 2
%matplotlib
from fix_scatter_new import *
import seaborn as sns

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Using matplotlib backend: Qt5Agg


In [58]:
# %time eyeTr = EyeDat()
dat = load_object("EyeDump.pcl")

In [130]:
F = dat.get_df(Health[1],3,1,"Fix",2)
S = dat.get_df(Health[1],3,1,"Simp")

In [134]:
cond,exp,trial = Health[2],1,2
disps, durations = np.array(dat.disps(cond,exp,trial)), dat.durations(cond,exp,trial)
X = disps
y = durations
D = np.column_stack((X,y))
D = D[~np.isnan(D).any(axis=1)]
D = D[~(D==0).any(axis=1)]
plt.scatter(D[:,0],D[:,1])
len(D),len(X),len(y)
plt.hist(durations[durations<800],bins = 100)

/home/ashedko/Projects/python/sci_stuff/fix_scatter_new.py:125: RuntimeWarning: invalid value encountered in double_scalars
  deltas = v - mean


0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []
0.0 []

(array([   2.,    3.,   94.,  107.,   94.,   62.,   57.,   51.,   71.,
          47.,   36.,   35.,   29.,   29.,   31.,   25.,   30.,   22.,
          35.,   31.,   28.,   30.,   21.,   34.,   32.,   38.,   32.,
          44.,   37.,   28.,   39.,   35.,   21.,   26.,   21.,   31.,
          27.,   32.,   25.,   24.,   25.,   19.,   15.,   18.,   14.,
          13.,   13.,   18.,   16.,   11.,   11.,    6.,   21.,   14.,
           8.,    7.,    9.,    4.,    8.,    8.,    4.,    7.,    4.,
           6.,    8.,    4.,    3.,    7.,    7.,    6.,    6.,    3.,
           7.,    4.,    5.,    6.,    6.,    5.,    5.,    6.,    6.,
           1.,    3.,    0.,    3.,    4.,    0.,    0.,    0.,    0.,
           3.,    2.,    2.,    1.,    2.,    1.,    2.,    1.,    2.,    2.]),
 array([   4.  ,   11.94,   19.88,   27.82,   35.76,   43.7 ,   51.64,
          59.58,   67.52,   75.46,   83.4 ,   91.34,   99.28,  107.22,
         115.16,  123.1 ,  131.04,  138.98,  146.92,  154.86,  162.8

In [129]:
S = [[ 143.5,  307.9],
 [ 144.5,  306.4],
 [ 145.3 , 306.9],
 [ 145.8 , 308.2],
 [ 145.6 , 308.9],
 [ 136.2  ,310.1],
 [ 135.8 , 312.4],
 [ 135.7  ,313.4],
 [ 135.5 , 316. ],
 [ 135.4  ,315.4],
 [ 135.2 , 313.2],
 [ 135.3,  318. ],
 [ 138.3,  320.2],
 [ 137.7,  320.4],
 [ 138.3,  318.4],
 [ 135.   ,315.2],
 [ 134.9 , 317.2],
 [ 134.  , 321.3]]
v = np.array(S)
length = len(v)
sum_x = np.sum(v[:, 0])
sum_y = np.sum(v[:, 1])
mean = np.array([sum_x/length,sum_y/length])
mean

array([ 138.44444444,  313.86111111])

In [54]:
f = [1,1,1]
for trial in range(3):
    f[trial], axarr = plt.subplots(3, 4,  figsize=(16, 12), dpi=160)
    i=0
    for cond in Health:
        for exp in range(1,5):
            # fn = fname(cond,exp,trial)
            # if cache and os.path.isfile(fn + ".npy"):
            #     print("cache\n")
            #     D = np.load(fn + ".npy")
            #     disps, durations = D[:, 0], D[:, 1]
            # else:
            axarr[i, exp-1].set_ylim(0,2000)
            disps, durations = dat.disps(cond,exp,trial), dat.durations(cond,exp,trial)
            D, clf = plot(disps, durations, axarr[i, exp-1])
            # np.save(fn, D)
        i+=1

/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/ashedko/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.

In [146]:
len(S)/F.tail(1)["CURRENT_FIX_END"]

861    0.501719
Name: CURRENT_FIX_END, dtype: float64

In [140]:
Fix = Fix.applymap(locale.atof)
def f(x):
    if x=='.': return None
    elif isinstance( x, int ) : return x
    else: return locale.atof(x) 
Simp = Simp.applymap(f)


In [36]:
health = Health[0]
exp = 1
patients = os.listdir("./Данные айтрекера/{}/".format(health))
fnames = [(glob.glob("./*/{}/{}/Fix*_{}*".format(health, pat, exp))[0],
                           glob.glob("./*/{}/{}/Simple*_{}*".format(health, pat, exp))[0]) for pat in patients]

Simp = []
with open(fnames[0][1]) as csvfile:
    local_cols = column_names_gaze
    reader = csv.DictReader(csvfile, delimiter='\t')
    for tup in reader:
        Simp.append([tup[fld] for fld in local_cols] + [reader.line_num - 2])

In [20]:
np.std([np.nan])

nan